FROM public.ecr.aws/docker/library/python:3.10-alpine

ENV FLASK_RUN_HOST=0.0.0.0

WORKDIR /

RUN adduser -D -u 1000 app

RUN apk update && \
    apk add \
    pcre \
    pcre-dev \
    build-base \
    gcc \
    linux-headers \
    openssl \
    libffi-dev \
    && pip install pipenv

RUN mkdir -p /var/www/app

COPY Pipfile* /app/

RUN cd /app && pipenv install --system --deploy

COPY . /app/

CMD ["flask", "--app", "app:app", "run", "--host=0.0.0.0", "--port=5000"]